<?php
/**
 * Product view template
 * @var $block \Magento\Catalog\Block\Product\View
 */

$_product = $block->getProduct();
?>
<div class="quotation">
    <div class="fieldset">
        <div class="field">
            <label for="zipcode" class="label"><?= __('Enter Zipcode')?></label>
            <div class="control">
                <input type="text" name="zipcode" id="zipcode" placeholder="12345-678" class="input-text" value="">
                <input type="hidden" name="weight" id="weight" class="input-text" value="<?= (float) $_product->getWeight();?>">
                <input type="hidden" name="width" id="width" class="input-text" value="<?= (float) $_product->getWidth();?>">
                <input type="hidden" name="height" id="height" class="input-text" value="<?= (float) $_product->getHeight();?>">
                <input type="hidden" name="length" id="length" class="input-text" value="<?= (float) $_product->getLength();?>">
                <small><?= __('Searching...')?></small>
            </div>
        </div>
        <div class="display-quotation">
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#zipcode" : {
            "AbraaoMarques_Correios/js/script": {}
        }
    }
</script>
